project:
  type: website
  render:
    - index.qmd
    - 00_welcome.qmd
    - 01a_r-rstudio.qmd
    - 01b_r-basics.qmd
    - 01c_r-data-structures.qmd
    - 01d_indexing.qmd
    - 01e_flow-control.qmd
    - 01g_tidyverse.qmd
    - 02a_rdm-intro.qmd
    - 02b_rstudio-projects.qmd
    - 02c_paths-proj-structure.qmd
    - 02d_filenaming.qmd
    - 03a_data-munging_iteration.qmd
    - 03b_dplyr_joins.qmd
    - 03c_functions.qmd
    - 04a_metadata_intro.qmd
    - 04b_dataspice.qmd
    - 04c_metadata_outro.qmd
    - 05a_datavis-intro.qmd
    - 05b_ggplot2-intro.qmd
    - 05c_exploratory.qmd
    - 06a_quarto-intro.qmd
    - 06b_create-report.qmd
    - 06c_code-chunks.qmd
    - 07b_evolottery.qmd
    - 08a_pkg_functions.qmd
    - 10_closing-slides.qmd
    - about.qmd
    - setup.qmd
    - APPENDIX_individual.qmd
    - APPENDIX_geolocate.qmd
    - APPENDIX_analysis.qmd
    - APPENDIX_report.qmd
    - APPENDIX_mypackage.qmd

website:
  title: "Reproducible Research Data and Project Management in R"
  favicon: /assets/favicon/favicon.ico
  page-footer:
    background: black
    center:
      - text: "Copyright 2024, ACCE DTP | R-RSE S.M.P.C."
  margin-header: |
    [![](/assets/logo/acce-dtp.webp)](https://accedtp.ac.uk/)
  page-navigation: true
  site-url: https://acce-rrresearch.netlify.app/
  back-to-top-navigation: true
  navbar:
    logo: assets/logo/r-rse-logo2.png
    logo-href: https://www.r-rse.eu/
    pinned: true
    search: true
    left:
      - href: index.qmd
        text: "{{< fa home >}} Home"
      - text: "{{< fa circle-info >}} About"
        href:  about.qmd
      - text: "Setup"
        href: setup.qmd
        icon: gear
      - text: "Credits"
        icon: megaphone
        href: credits.qmd

  sidebar:
    style: "docked"
    search: true
    border: true
    contents:
      - section: "INTRODUCTION"
        contents:
          - file: 00_welcome.qmd
            text: "Welcome"
      - section: "BASICS"
        contents:
          - 01a_r-rstudio.qmd
          - 01b_r-basics.qmd
          - 01c_r-data-structures.qmd
          - 01d_indexing.qmd
          - 01e_flow-control.qmd
          - 01g_tidyverse.qmd
      - section: "PROJECT MANAGEMENT"
        contents:
          - 02a_rdm-intro.qmd
          - 02b_rstudio-projects.qmd
          - 02c_paths-proj-structure.qmd
          - 02d_filenaming.qmd
      - section: "DATA MUNGING"
        contents:
          - 03a_data-munging_iteration.qmd
          - 03b_dplyr_joins.qmd
          - 03c_functions.qmd
      - section: "METADATA"
        contents:
          - 04a_metadata_intro.qmd
          - 04b_dataspice.qmd
          - 04c_metadata_outro.qmd
      - section: "PLOTTING with ggplot2"
        contents:
          - 05a_datavis-intro.qmd
          - 05b_ggplot2-intro.qmd
          - 05c_exploratory.qmd
      - section: "REPORTING with Quarto"
        contents:
          - 06a_quarto-intro.qmd
          - 06b_create-report.qmd
          - 06c_code-chunks.qmd
      - section: "VERSION CONTROL"
        contents:
          - 07b_evolottery.qmd
      - section: "PACKAGING CODE"
        contents:
          - 08a_pkg_functions.qmd
      - section: "RESEARCH COMPENDIA"
        contents:
      - section: "CLOSING"
        contents:
          - 10_closing-slides.qmd
      - section: "APPENDICES"
        contents:
          - APPENDIX_individual.qmd
          - APPENDIX_geolocate.qmd
          - APPENDIX_analysis.qmd
          - APPENDIX_report.qmd
          - APPENDIX_mypackage.qmd
      - section: "LICENSE"
        contents:
          - text: "CC BY-SA"
            icon: file-contract
            href: https://creativecommons.org/licenses/by-sa/4.0/

bibliography: appendices/data-raw/wood-survey-data-master/references.bib

format:
  html:
    theme:
      - cosmo
      - assets/css/styles.scss
    code-copy: true
    toc: true
    code-overflow: wrap
    code-link: true
    fig-responsive: true
    highlight-style: "pygments"
    linkcolor: "#388274ff"
    primary: "#388274ff"
    code-block-border-left: "#5bb3a7ff"
    monobackgroundcolor: "#d2eaf0"
    lightbox: true
    from: markdown+emoji

editor: visual

execute:
  freeze: auto

plugins:
  package: "@quarto/netlify-plugin-quarto"

license: "CC BY-SA"

