default:
  course_title: "Reproducible Research Data and Project Management in R"
  hackpad_url: "http://bit.ly/acce21-notepad"
  course_instructor: "Dr Anna Krystalli"
  github_repo: "r-rse/rrresearch-acce-rrse"
  escaped_url: "https://annakrystalli.me/rrresearchACCE20"
  course_dates: "April 2024"
  location: "Online"
  book_url: "https://annakrystalli.me/rrresearchACCE20/"
  bitly_url: "http://bit.ly/ACCE-book"
  output_dir: "_book"
  pkgdev_date_iso: "2021-05-07"
  day1: "April 12th"
  day2: "April 15th"
  day3: "April 17th"
  day4: "April 19th"
  year: "2024"
