---
title: "code-chunks"
author: "Anna Krystalli"
date: "10/09/2019"
output: html_document
---


```{r libraries, include=FALSE}

```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, 
                      dev="cairo_pdf", fig.width=7, fig.height=3.5)
# load libraries
library(dplyr)
library(readr)
library(ggplot2)
library(ggthemes)
library(rrcompendium) # added rrcompendium
```

```{r set-theme}

```

```{r set-theme}
# set plot theme
theme_set(theme_grey())
```

<!-- Figure 1: Gillespie simulations -->
```{r figure1, fig.cap="Population dynamics from a Gillespie simulation of the Levins model with large (N=1000, panel A) and small (N=100, panel B) number of sites (blue) show relatively weaker effects of demographic noise in the bigger system. Models are otherwise identical, with e = 0.2 and c = 1 (code in appendix A). Theoretical predictions for mean and plus/minus one standard deviation shown in horizontal re dashed lines."}

```


<!-- Figure 1: Gillespie simulations -->
```{r figure1, fig.cap="Population dynamics from a Gillespie simulation of the Levins model with large (N=1000, panel A) and small (N=100, panel B) number of sites (blue) show relatively weaker effects of demographic noise in the bigger system. Models are otherwise identical, with e = 0.2 and c = 1 (code in appendix A). Theoretical predictions for mean and plus/minus one standard deviation shown in horizontal re dashed lines."}
# create colour palette
colours <- ptol_pal()(2)
# load-data
data <- read_csv(here::here("analysis", "data","raw_data", "gillespie.csv"), 
                  col_types = "cdiddd") 
# recode-data
data <- data %>% 
  mutate(system_size = recode(system_size, 
                              large = "A. 1000 total sites", 
                              small = "B. 100 total sites")) 

# plot-gillespie
data %>% 
    ggplot(aes(x = time)) + 
    geom_hline(aes(yintercept = mean), lty=2, col=colours[2]) + 
    geom_hline(aes(yintercept = minus_sd), lty=2, col=colours[2]) + 
    geom_hline(aes(yintercept = plus_sd), lty=2, col=colours[2]) + 
    geom_line(aes(y = n), col=colours[1]) +
    facet_wrap(~system_size, scales = "free_y") 
```

